# Copyright (C) 2020 The Dofus Fashionista
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

"""Emit fashionsite/chardata/dynamic_translations.py; run after any data update.

Item types, stat names, elements and slots are translated at runtime with
gettext(variable), which makemessages cannot see: without this generated module
of gettext_noop() calls, --no-obsolete purges their catalog entries.
"""

import os
import sqlite3
import sys

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(CURRENT_DIR)
sys.path.insert(0, os.path.join(ROOT, 'fashionistapulp'))

from fashionistapulp.game_versions import GAME_VERSIONS, dofus_versions

# The Dofus versions only, from the registry rather than a list written out by
# hand that goes stale the day a version is added.
#
# Wakfu is deliberately not here. Its type and stat names are Ankama's own and
# the data carries them in French, Spanish and Portuguese already, so asking a
# translator for them would invent a second set of words for things the game
# has already named. They are stored beside the items instead; German is the
# one language Wakfu has never had, and it falls back to English.
DBS = [GAME_VERSIONS[key].db_file for key in dofus_versions()]
OUT = os.path.join(ROOT, 'fashionsite', 'chardata', 'dynamic_translations.py')

HEADER = '''\
# AUTO-GENERATED by itemscraper/generate_dynamic_translations.py -- do not
# edit by hand. Strings translated at runtime from DATA (gettext(variable)):
# item types, stat names, elements and slots of every game version.
# makemessages scans this file, so their catalog entries survive
# makemessages --no-obsolete.
from django.utils.translation import gettext_noop

DYNAMIC_DATA_STRINGS = [
'''


def main():
    strings = set()

    for db in DBS:
        path = os.path.join(ROOT, 'fashionistapulp', 'fashionistapulp', db)
        if not os.path.exists(path):
            print('missing db, skipping:', db)
            continue
        con = sqlite3.connect(path)
        for table, column in (('item_types', 'name'), ('stats', 'name'),
                              ('weapontype', 'name')):
            try:
                rows = con.execute('SELECT DISTINCT %s FROM %s' % (column, table)).fetchall()
            except sqlite3.OperationalError:
                continue
            strings.update(r[0] for r in rows if r[0])
        con.close()

    from fashionistapulp.dofus_constants import (ELEMENT_KEY_TO_NAME,
                                                 SLOT_NAME_TO_TYPE,
                                                 STAT_NAME_TO_KEY)
    strings.update(v for v in ELEMENT_KEY_TO_NAME.values() if v)
    strings.update(v for v in SLOT_NAME_TO_TYPE.values() if v)
    # STAT_NAME_TO_KEY keys are the display names the views translate.
    strings.update(k for k in STAT_NAME_TO_KEY if k)

    # STAT_TRANSLATE values (get_equipments2.py) are the canonical strings the site
    # renders and translates at runtime. Read via AST: importing it runs its argparse.
    import ast
    tree = ast.parse(open(os.path.join(CURRENT_DIR, 'get_equipments2.py'),
                          encoding='utf-8').read())
    for node in ast.walk(tree):
        if (isinstance(node, ast.Assign) and node.targets
                and isinstance(node.targets[0], ast.Name)
                and node.targets[0].id == 'STAT_TRANSLATE'
                and isinstance(node.value, ast.Dict)):
            for value in node.value.values:
                if isinstance(value, ast.Constant) and isinstance(value.value, str)                         and value.value.strip():
                    strings.add(value.value)

    lines = [HEADER]
    for s in sorted(strings):
        lines.append('    gettext_noop(%r),\n' % s)
    lines.append(']\n')
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(''.join(lines))
    print('wrote %d dynamic strings to %s' % (len(strings), OUT))


if __name__ == '__main__':
    main()
