# Copyright (C) 2026 The Dofus Fashionista, LGPL (see COPYING.LESSER)
"""The name each game gives a forgemagie rune, in the reader's language.

The workshop builds its rune names in code, from French abbreviations:
`Rune %s %s`. That string is the KEY the rest of the tool joins on, and it is
what a session stores in the reader's browser, so it stays French. What the
reader is shown is another matter: Ankama renames every rune in every client,
and the workshop was showing the French spelling to all five languages.

    Rune de Terre | Earth Rune | Runa de Tierra | Runa de Terra | Rune der Erde

Each version is read from its own table (105 runes on Dofus 3 and the Beta,
98 on Dofus 2, 86 on Touch, 57 on Retro), regenerated by
scripts/generate_rune_names.py.
"""
import json
import os

_PATH = os.path.join(os.path.dirname(__file__), 'forgemagie_rune_names.json')
_CACHE = None

#: L'ordre de repli quand la langue du lecteur ne repond pas: l'anglais, puis
#: la clef francaise elle-meme, qui est toujours un nom valide du jeu.
_FALLBACK = ('en', 'fr')


def _load():
    global _CACHE
    if _CACHE is None:
        try:
            with open(_PATH, encoding='utf-8') as handle:
                _CACHE = json.load(handle)
        except (IOError, OSError, ValueError):
            _CACHE = {}
    return _CACHE


def rune_display_name(game_version, french_name, language):
    """What this version's client calls that rune, in the reader's language.

    Falls back to the French key rather than to nothing: the key is itself a
    name the game uses, so a missing entry costs the translation, never the
    label.
    """
    names = (_load().get(game_version) or {}).get(french_name) or {}
    for candidate in ((language or '').split('-')[0],) + _FALLBACK:
        if candidate and names.get(candidate):
            return names[candidate]
    return french_name


def known_rune_names(game_version):
    """{french name: {language: name}} for one version, for the guards."""
    return _load().get(game_version) or {}
