# AUTO-GENERATED by itemscraper/get_spells_retro.py -- do not edit by hand.
# Dofus Retro (1.29) damage spells per class, decoded from the spell lang.
from .dofus_constants import Spell, Effects, EARTH, FIRE, WATER, AIR, NEUTRAL

RETRO_DAMAGE_SPELLS = {
    "Feca": [
        Spell("Retour du bâton", [1, 1, 1, 1, 1, 100], Effects(
            [["16-18", "18-21", "10-24", "12-26", "16-30", "21-35"]],
            [["6-20", "8-22", "20-24", "22-27", "26-32", "31-37"]],
            [NEUTRAL],
        )),
        Spell("Bulle", [1, 1, 1, 1, 1, 100], Effects(
            [["9-13", "9-15", "11-17", "11-19", "13-21", "16-24"]],
            [["11-15", "11-17", "13-19", "13-21", "15-23", "18-26"]],
            [WATER],
        )),
        Spell("Attaque Nuageuse", [1, 1, 1, 1, 1, 100], Effects(
            [["11-11", "13-13", "4-15", "5-16", "7-18", "11-22"]],
            [["2-13", "3-14", "16-16", "18-18", "20-20", "25-25"]],
            [FIRE],
        )),
        Spell("Aveuglement", [1, 1, 1, 1, 1, 100], Effects(
            [["1-1", "2-3", "2-4", "2-5", "3-7", "6-15"]],
            [["2-2", "4-4", "5-5", "6-6", "8-8", "16-16"]],
            [NEUTRAL],
        )),
        Spell("Attaque Naturelle", [1, 1, 1, 1, 1, 100], Effects(
            [["2-6", "3-7", "4-8", "5-9", "7-11", "9-13"]],
            [["8-8", "9-9", "10-10", "11-11", "13-13", "15-15"]],
            [FIRE],
        )),
    ],
    "Osamodas": [
        Spell("Frappe du Craqueleur", [1, 1, 1, 1, 1, 100], Effects(
            [["6-25", "9-28", "12-31", "15-34", "18-37", "18-37"]],
            [["27-27", "30-30", "33-33", "36-36", "39-39", "39-39"]],
            [FIRE],
        )),
        Spell("Griffe Cinglante", [1, 1, 1, 1, 1, 100], Effects(
            [["6-9", "7-10", "8-11", "9-12", "11-14", "11-14"]],
            [["9-12", "10-13", "11-14", "12-15", "14-17", "14-17"]],
            [WATER],
        )),
        Spell("Corbeau", [1, 1, 1, 1, 1, 100], Effects(
            [["1-3", "1-3", "1-4", "1-5", "1-7", "3-10"]],
            [["3-5", "4-6", "5-7", "6-8", "7-9", "12-12"]],
            [FIRE],
        )),
        Spell("Fouet", [1, 1, 1, 1, 1, 100], Effects(
            [["51-55", "71-75", "91-95", "111-115", "151-155", "301-305"]],
            [["101-110", "141-150", "181-190", "221-230", "301-310", "601-610"]],
            [NEUTRAL],
        )),
        Spell("Griffe Spectrale", [1, 1, 1, 1, 1, 100], Effects(
            [["4-7", "5-8", "6-9", "7-10", "9-12", "13-22"]],
            [["6-11", "7-12", "8-13", "9-14", "11-16", "24-24"]],
            [FIRE],
        )),
    ],
    "Enutrof": [
        Spell("Pelle Massacrante", [1, 1, 1, 1, 1, 100], Effects(
            [["29-34", "31-36", "33-38", "35-40", "37-42", "45-50"]],
            [["36-41", "38-43", "40-45", "42-47", "44-49", "53-58"]],
            [WATER],
        )),
        Spell("Pelle du Jugement", [1, 1, 1, 1, 1, 100], Effects(
            [["2-10", "4-12", "6-14", "8-16", "10-18", "12-20"]],
            [["5-13", "7-15", "9-17", "11-19", "13-21", "15-23"]],
            [WATER],
        )),
        Spell("Roulage de Pelle", [1, 1, 1, 1, 1, 100], Effects(
            [["1-7", "2-8", "3-9", "4-10", "6-12", "9-15"]],
            [["8-8", "9-9", "10-10", "11-11", "12-12", "15-15"]],
            [FIRE],
        )),
        Spell("Désinvocation", [1, 1, 1, 1, 1, 100], Effects(
            [["31-50", "31-60", "31-70", "31-80", "51-110", "71-130"]],
            [["81-81", "91-91", "101-101", "111-111", "121-121", "130-130"]],
            [AIR],
        )),
        Spell("Force de l'Age", [1, 1, 1, 1, 1, 100], Effects(
            [["7-11", "9-13", "11-15", "13-17", "16-20", "21-25"]],
            [["10-14", "12-16", "14-18", "16-20", "19-23", "25-25"]],
            [AIR],
        )),
        Spell("Remblai", [1, 1, 1, 1, 1, 100], Effects(
            [["2-3", "3-5", "4-7", "5-9", "6-11", "7-12"]],
            [["5-5", "7-7", "9-9", "11-11", "13-13", "15-15"]],
            [EARTH],
        )),
        Spell("Pelle Fantomatique", [1, 1, 1, 1, 1, 100], Effects(
            [["6-10", "7-11", "8-12", "9-13", "10-14", "16-20"]],
            [["6-10", "7-11", "8-12", "9-13", "10-14", "20-20"]],
            [FIRE],
        )),
        Spell("Lancer de Pièces", [1, 1, 1, 1, 1, 100], Effects(
            [["1-2", "1-3", "1-4", "1-5", "1-6", "1-8"]],
            [["6-6", "8-8", "10-10", "12-12", "14-14", "16-16"]],
            [WATER],
        )),
        Spell("Lancer de Pelle", [1, 1, 1, 1, 1, 100], Effects(
            [["2-5", "3-6", "4-8", "5-10", "8-13", "11-16"]],
            [["6-6", "8-8", "11-11", "15-15", "21-21", "25-25"]],
            [EARTH],
        )),
    ],
    "Xelor": [
        Spell("Frappe de Xélor", [1, 1, 1, 1, 1, 100], Effects(
            [["26-30", "31-35", "36-40", "41-45", "41-45", "41-45"]],
            [["31-35", "36-40", "41-45", "46-50", "46-50", "46-50"]],
            [EARTH],
        )),
        Spell("Horloge", [1, 1, 1, 1, 1, 100], Effects(
            [["21-25", "24-28", "27-31", "27-31", "31-35", "31-35"]],
            [["26-30", "29-33", "30-34", "30-34", "36-40", "36-40"]],
            [WATER],
        )),
        Spell("Poussière Temporelle", [1, 1, 1, 1, 1, 100], Effects(
            [["1-10", "1-10", "3-12", "4-13", "6-15", "9-20"]],
            [["5-14", "5-14", "7-16", "8-17", "10-19", "16-27"]],
            [FIRE],
        )),
        Spell("Flétrissement", [1, 1, 1, 1, 1, 100], Effects(
            [["8-11", "9-13", "10-15", "11-17", "12-19", "15-24"]],
            [["10-13", "11-15", "12-17", "13-19", "14-21", "17-26"]],
            [AIR],
        )),
        Spell("Rayon Obscur", [1, 1, 1, 1, 1, 100], Effects(
            [["5-9", "6-11", "7-13", "8-15", "9-17", "13-29"]],
            [["10-14", "11-16", "12-18", "13-20", "14-22", "18-34"]],
            [FIRE],
        )),
        Spell("Sablier de Xélor", [1, 1, 1, 1, 1, 100], Effects(
            [["1-4", "1-6", "1-8", "2-9", "3-10", "6-13"]],
            [["4-7", "4-9", "4-11", "5-12", "6-13", "11-18"]],
            [FIRE],
        )),
        Spell("Gelure", [1, 1, 1, 1, 1, 100], Effects(
            [["5-10", "6-11", "7-12", "8-13", "9-14", "10-15"]],
            [["11-11", "12-12", "13-13", "14-14", "15-15", "16-16"]],
            [AIR],
        )),
        Spell("Aiguille", [1, 1, 1, 1, 1, 100], Effects(
            [["4-8", "5-9", "6-10", "7-11", "8-12", "12-22"]],
            [["9-9", "10-10", "11-11", "12-12", "13-13", "25-25"]],
            [FIRE],
        )),
    ],
    "Ecaflip": [
        Spell("Destin d'Ecaflip", [1, 1, 1, 1, 1, 100], Effects(
            [["1-20", "4-23", "7-26", "10-29", "13-37", "13-37"]],
            [["13-75", "13-75", "13-75", "13-75", "13-75", "13-75"]],
            [EARTH],
        )),
        Spell("Rekop", [1, 1, 1, 1, 1, 100], Effects(
            [["11-20", "11-25", "11-30", "11-35", "12-41", "12-41"], ["11-20", "11-25", "11-30", "11-35", "12-41", "12-41"], ["11-20", "11-25", "11-30", "11-35", "12-41", "12-41"], ["11-20", "11-25", "11-30", "11-35", "12-41", "12-41"]],
            [["11-20", "11-25", "11-30", "11-35", "12-41", "12-41"], ["11-20", "11-25", "11-30", "11-35", "12-41", "12-41"], ["11-20", "11-25", "11-30", "11-35", "12-41", "12-41"], ["11-20", "11-25", "11-30", "11-35", "12-41", "12-41"]],
            [EARTH, WATER, FIRE, AIR],
        )),
        Spell("Griffe de Ceangal", [1, 1, 1, 1, 1, 100], Effects(
            [["13-25", "13-28", "13-31", "13-34", "15-39", "21-45"]],
            [["13-25", "13-28", "13-31", "13-34", "15-39", "21-45"]],
            [EARTH],
        )),
        Spell("Griffe Joueuse", [1, 1, 1, 1, 1, 100], Effects(
            [["10-15", "12-17", "14-19", "18-23", "21-26", "24-29"]],
            [["16-16", "18-18", "20-20", "25-25", "30-30", "35-35"]],
            [EARTH],
        )),
        Spell("Esprit Félin", [1, 1, 1, 1, 1, 100], Effects(
            [["11-20", "16-25", "21-30", "21-35", "26-40", "36-50"]],
            [["20-20", "25-25", "30-30", "35-35", "40-40", "50-50"]],
            [EARTH],
        )),
        Spell("Langue Râpeuse", [1, 1, 1, 1, 1, 100], Effects(
            [["3-12", "5-14", "7-16", "9-18", "11-20", "16-25"]],
            [["6-15", "8-17", "8-17", "11-20", "13-22", "18-27"]],
            [FIRE],
        )),
        Spell("Topkaj", [1, 1, 1, 1, 1, 100], Effects(
            [["8-20", "10-22", "12-24", "16-28", "18-30", "19-31"]],
            [["12-24", "14-26", "16-28", "18-30", "20-32", "22-34"]],
            [FIRE],
        )),
        Spell("Tout ou rien", [1, 1, 1, 1, 1, 100], Effects(
            [["2-7", "3-12", "3-17", "3-22", "4-28", "4-38"]],
            [["3-14", "5-24", "5-34", "5-44", "7-56", "7-76"]],
            [NEUTRAL],
        )),
        Spell("Bluff", [1, 1, 1, 1, 1, 100], Effects(
            [["1-22", "1-25", "1-28", "1-35", "1-45", "1-50"], ["1-22", "1-25", "1-28", "1-35", "1-45", "1-50"]],
            [["25-25", "28-28", "33-33", "40-40", "50-50", "55-55"], ["25-25", "28-28", "33-33", "40-40", "50-50", "55-55"]],
            [WATER, AIR],
        )),
        Spell("Pile ou Face", [1, 1, 1, 1, 1, 100], Effects(
            [["4-11", "4-12", "4-13", "4-14", "4-15", "6-19"]],
            [["4-12", "4-13", "4-14", "4-15", "4-17", "9-24"]],
            [EARTH],
        )),
    ],
    "Eniripsa": [
        Spell("Mot Blessant", [1, 1, 1, 1, 1, 100], Effects(
            [["8-10", "9-11", "10-12", "11-13", "12-14", "16-18"]],
            [["11-11", "12-12", "13-13", "14-14", "15-15", "19-19"]],
            [AIR],
        )),
        Spell("Mot Interdit", [1, 1, 1, 1, 1, 100], Effects(
            [["3-8", "4-9", "5-10", "6-11", "8-13", "11-16"]],
            [["9-9", "11-11", "13-13", "15-15", "19-19", "25-25"]],
            [FIRE],
        )),
    ],
    "Iop": [
        Spell("Colère de Iop", [1, 1, 1, 1, 1, 100], Effects(
            [["43-62", "44-63", "45-64", "46-65", "47-66", "51-70"]],
            [["53-72", "54-73", "55-74", "56-75", "57-76", "61-80"]],
            [EARTH],
        )),
        Spell("Epée de Iop", [1, 1, 1, 1, 1, 100], Effects(
            [["10-30", "10-30", "11-33", "12-36", "13-39", "13-39"]],
            [["15-35", "15-35", "16-38", "17-41", "18-44", "18-44"]],
            [EARTH],
        )),
        Spell("Concentration", [1, 1, 1, 1, 1, 100], Effects(
            [["2-10", "4-12", "6-14", "6-14", "9-17", "13-21"]],
            [["7-15", "9-17", "11-19", "11-19", "14-22", "18-26"]],
            [EARTH],
        )),
        Spell("Epée Céleste", [1, 1, 1, 1, 1, 100], Effects(
            [["11-20", "16-25", "21-30", "26-35", "26-40", "26-40"]],
            [["16-25", "21-30", "26-35", "31-40", "41-55", "41-55"]],
            [AIR],
        )),
        Spell("Tempête de Puissance", [1, 1, 1, 1, 1, 100], Effects(
            [["21-25", "24-28", "27-31", "31-35", "36-40", "36-40"]],
            [["26-30", "29-33", "32-36", "36-40", "41-45", "41-45"]],
            [FIRE],
        )),
        Spell("Epée du Jugement", [1, 1, 1, 1, 1, 100], Effects(
            [["1-27", "1-30", "1-35", "1-35", "1-40", "1-40"]],
            [["1-32", "1-35", "1-40", "1-40", "1-45", "1-45"]],
            [AIR],
        )),
        Spell("Couper", [1, 1, 1, 1, 1, 100], Effects(
            [["3-8", "4-9", "5-10", "6-11", "8-13", "11-16"]],
            [["9-9", "10-10", "11-11", "12-12", "13-13", "20-20"]],
            [FIRE],
        )),
        Spell("Epée Destructrice", [1, 1, 1, 1, 1, 100], Effects(
            [["6-20", "7-24", "8-28", "9-32", "10-36", "11-40"]],
            [["21-22", "25-26", "29-30", "33-34", "37-38", "41-42"]],
            [FIRE],
        )),
        Spell("Epée du destin", [1, 1, 1, 1, 1, 100], Effects(
            [["4-11", "5-12", "6-13", "7-14", "8-15", "10-17"]],
            [["12-12", "13-13", "14-14", "15-15", "16-16", "18-18"]],
            [FIRE],
        )),
        Spell("Epée Divine", [1, 1, 1, 1, 1, 100], Effects(
            [["5-14", "6-15", "7-16", "8-17", "9-18", "11-20"]],
            [["15-15", "16-16", "17-17", "18-18", "19-19", "21-21"]],
            [AIR],
        )),
        Spell("Intimidation", [1, 1, 1, 1, 1, 100], Effects(
            [["1-2", "2-3", "3-4", "4-5", "5-6", "5-9"]],
            [["3-4", "3-4", "3-4", "5-6", "6-7", "6-10"]],
            [NEUTRAL],
        )),
        Spell("Pression", [1, 1, 1, 1, 1, 100], Effects(
            [["5-9", "6-10", "6-10", "7-11", "8-12", "9-13"]],
            [["7-11", "8-12", "8-12", "9-13", "10-14", "11-15"]],
            [EARTH],
        )),
    ],
    "Cra": [
        Spell("Flèche Explosive", [1, 1, 1, 1, 1, 100], Effects(
            [["16-20", "17-21", "18-22", "19-23", "20-24", "20-24"]],
            [["22-26", "23-27", "25-29", "27-31", "28-32", "28-32"]],
            [FIRE],
        )),
        Spell("Flèche Ralentissante", [1, 1, 1, 1, 1, 100], Effects(
            [["13-15", "15-17", "17-19", "19-21", "21-23", "21-23"]],
            [["18-20", "21-23", "23-25", "27-29", "29-31", "29-31"]],
            [WATER],
        )),
        Spell("Flèche Destructrice", [1, 1, 1, 1, 1, 100], Effects(
            [["13-15", "15-17", "17-19", "19-21", "21-23", "26-28"]],
            [["18-20", "21-23", "23-25", "27-29", "29-31", "36-38"]],
            [EARTH],
        )),
        Spell("Flèche Persécutrice", [1, 1, 1, 1, 1, 100], Effects(
            [["2-4", "3-5", "4-6", "5-7", "6-8", "11-13"], ["2-4", "3-5", "4-6", "5-7", "6-8", "11-13"]],
            [["3-5", "4-6", "6-8", "8-10", "9-11", "14-16"], ["3-5", "4-6", "6-8", "8-10", "9-11", "14-16"]],
            [FIRE, AIR],
        )),
        Spell("Flèche Cinglante", [1, 1, 1, 1, 1, 100], Effects(
            [["6-7", "7-8", "8-9", "9-10", "10-11", "13-14"]],
            [["8-9", "9-10", "11-12", "12-13", "13-14", "17-18"]],
            [EARTH],
        )),
        Spell("Flèche Harcelante", [1, 1, 1, 1, 1, 100], Effects(
            [["5-7", "6-8", "7-9", "8-10", "9-11", "13-15"]],
            [["7-9", "8-10", "10-12", "11-13", "12-14", "17-19"]],
            [AIR],
        )),
        Spell("Flèche Punitive", [1, 1, 1, 1, 1, 100], Effects(
            [["15-17", "17-19", "19-21", "23-25", "25-27", "31-33"]],
            [["20-22", "22-24", "23-25", "29-31", "30-32", "37-39"]],
            [EARTH],
        )),
        Spell("Flèche d'Immobilisation", [1, 1, 1, 1, 1, 100], Effects(
            [["3-4", "4-5", "5-6", "6-7", "7-8", "9-10"]],
            [["4-5", "5-6", "6-7", "9-10", "10-11", "12-13"]],
            [WATER],
        )),
        Spell("Flèche d'Expiation", [1, 1, 1, 1, 1, 100], Effects(
            [["23-25", "25-27", "27-29", "29-31", "31-33", "37-39"]],
            [["27-29", "30-32", "32-34", "35-37", "37-39", "43-45"]],
            [WATER],
        )),
        Spell("Flèche Enflammée", [1, 1, 1, 1, 1, 100], Effects(
            [["13-15", "14-16", "15-17", "16-18", "17-19", "21-23"]],
            [["16-18", "17-19", "19-21", "20-22", "22-24", "27-29"]],
            [FIRE],
        )),
        Spell("Flèche Glacée", [1, 1, 1, 1, 1, 100], Effects(
            [["4-6", "5-7", "6-8", "7-9", "8-10", "9-10"]],
            [["6-8", "7-9", "8-10", "9-11", "11-13", "12-13"]],
            [FIRE],
        )),
        Spell("Flèche Magique", [1, 1, 1, 1, 1, 100], Effects(
            [["9-11", "10-12", "11-13", "12-14", "13-15", "20-22"]],
            [["11-13", "12-14", "13-15", "14-16", "15-17", "24-26"]],
            [FIRE],
        )),
        Spell("Flèche Empoisonnée", [1, 1, 1, 1, 1, 100], Effects(
            [["2-3", "3-4", "4-5", "5-6", "6-7", "9-10"]],
            [["5-5", "6-6", "7-7", "8-8", "9-9", "12-12"]],
            [NEUTRAL],
        )),
        Spell("Flèche de Recul", [1, 1, 1, 1, 1, 100], Effects(
            [["11-14", "12-15", "13-16", "14-17", "15-18", "18-21"]],
            [["13-16", "14-17", "15-18", "17-20", "18-21", "21-24"]],
            [AIR],
        )),
    ],
    "Sadida": [
        Spell("Feu de Brousse", [1, 1, 1, 1, 1, 100], Effects(
            [["3-5", "3-6", "3-7", "4-8", "6-10", "6-10"], ["3-5", "3-6", "3-7", "4-8", "6-10", "6-10"]],
            [["6-6", "7-7", "8-8", "9-9", "11-11", "11-11"], ["6-6", "7-7", "8-8", "9-9", "11-11", "11-11"]],
            [WATER, FIRE],
        )),
        Spell("Herbe Folle", [1, 1, 1, 1, 1, 100], Effects(
            [["2-5", "3-7", "4-8", "5-9", "6-10", "11-20"]],
            [["8-8", "10-10", "12-12", "14-14", "16-16", "25-25"]],
            [FIRE],
        )),
        Spell("Ronces Agressives", [1, 1, 1, 1, 1, 100], Effects(
            [["6-30", "6-35", "6-40", "6-45", "6-50", "6-65"]],
            [["36-36", "41-41", "46-46", "51-51", "56-56", "65-65"]],
            [EARTH],
        )),
        Spell("Vent Empoisonné", [1, 1, 1, 1, 1, 100], Effects(
            [["3-3", "4-4", "4-4", "4-4", "5-5", "8-8"]],
            [["4-4", "5-5", "5-5", "5-5", "6-6", "10-10"]],
            [NEUTRAL],
        )),
        Spell("Ronces Multiples", [1, 1, 1, 1, 1, 100], Effects(
            [["6-8", "7-9", "8-10", "10-12", "12-14", "16-18"]],
            [["10-10", "11-11", "12-12", "14-14", "15-15", "19-19"]],
            [EARTH],
        )),
        Spell("Tremblement", [1, 1, 1, 1, 1, 100], Effects(
            [["2-2", "3-3", "3-3", "4-4", "5-5", "7-7"]],
            [["4-4", "6-6", "6-6", "8-8", "10-10", "12-12"]],
            [FIRE],
        )),
        Spell("Larme", [1, 1, 1, 1, 1, 100], Effects(
            [["11-15", "11-17", "11-19", "11-21", "14-24", "17-27"]],
            [["16-17", "18-19", "20-21", "22-23", "24-25", "26-27"]],
            [WATER],
        )),
        Spell("Ronce", [1, 1, 1, 1, 1, 100], Effects(
            [["4-6", "6-8", "6-10", "9-13", "10-17", "11-18"]],
            [["8-8", "10-10", "12-12", "16-16", "20-20", "22-22"]],
            [EARTH],
        )),
    ],
    "Sacrier": [
        Spell("Furie", [1, 1, 1, 1, 1, 100], Effects(
            [["6-10", "7-11", "8-12", "9-13", "9-13", "9-13"]],
            [["11-15", "11-15", "11-15", "11-15", "11-15", "11-15"]],
            [WATER],
        )),
        Spell("Assaut", [1, 1, 1, 1, 1, 100], Effects(
            [["5-9", "6-10", "7-11", "8-12", "11-15", "13-19"]],
            [["8-12", "9-13", "10-14", "11-15", "16-20", "19-25"]],
            [AIR],
        )),
        Spell("Pied du Sacrieur", [1, 1, 1, 1, 1, 100], Effects(
            [["5-9", "7-11", "8-14", "9-17", "10-18", "13-22"]],
            [["11-11", "13-13", "15-15", "17-17", "20-20", "25-25"]],
            [EARTH],
        )),
    ],
    "Pandawa": [
        Spell("Pandatak", [1, 1, 1, 1, 1, 100], Effects(
            [["11-15", "14-18", "16-21", "19-26", "23-32", "26-35"]],
            [["14-18", "17-21", "21-26", "26-33", "31-35", "36-40"]],
            [EARTH],
        )),
        Spell("Flasque Explosive", [1, 1, 1, 1, 1, 100], Effects(
            [["6-15", "6-17", "8-19", "9-23", "11-25", "16-30"]],
            [["9-18", "11-20", "13-24", "16-30", "21-35", "26-40"]],
            [FIRE],
        )),
        Spell("Vague à Lame", [1, 1, 1, 1, 1, 100], Effects(
            [["11-20", "13-22", "16-25", "16-30", "19-33", "22-36"]],
            [["15-24", "17-26", "21-30", "26-35", "31-40", "36-45"]],
            [WATER],
        )),
        Spell("Souffle Alcoolisé", [1, 1, 1, 1, 1, 100], Effects(
            [["7-12", "9-14", "11-16", "11-18", "11-20", "13-22"]],
            [["9-14", "11-16", "13-18", "13-20", "13-22", "15-24"]],
            [AIR],
        )),
        Spell("Gueule de Bois", [1, 1, 1, 1, 1, 100], Effects(
            [["7-11", "7-13", "8-14", "9-16", "11-19", "14-22"]],
            [["9-13", "9-15", "10-16", "11-18", "13-21", "16-24"]],
            [EARTH],
        )),
        Spell("Poing Enflammé", [1, 1, 1, 1, 1, 100], Effects(
            [["7-11", "8-12", "9-13", "9-14", "10-15", "16-21"]],
            [["9-13", "10-14", "11-15", "11-16", "12-17", "19-24"]],
            [FIRE],
        )),
    ],
    'default': [],
}

RETRO_SPELL_NAMES = {
 "Retour du bâton": {
  "fr": "Retour du bâton",
  "en": "Backlash",
  "es": "Puñalada",
  "pt": "Troco",
  "de": "Gegenangriff"
 },
 "Bulle": {
  "fr": "Bulle",
  "en": "Bubble",
  "es": "Pompa",
  "pt": "Bolha",
  "de": "Blase"
 },
 "Attaque Nuageuse": {
  "fr": "Attaque Nuageuse",
  "en": "Cloudy Attack",
  "es": "Ataque Nuboso",
  "pt": "Ataque Nebuloso",
  "de": "Nebelhafter Angriff"
 },
 "Aveuglement": {
  "fr": "Aveuglement",
  "en": "Blindness",
  "es": "Ceguera",
  "pt": "Cegueira",
  "de": "Blindheit"
 },
 "Attaque Naturelle": {
  "fr": "Attaque Naturelle",
  "en": "Natural Attack",
  "es": "Ataque Natural",
  "pt": "Ataque Natural",
  "de": "Natürlicher Angriff"
 },
 "Frappe du Craqueleur": {
  "fr": "Frappe du Craqueleur",
  "en": "Punch of the Crackler",
  "es": "Golpe del Crujidor",
  "pt": "Soco de Crackler",
  "de": "Krachlerfaust"
 },
 "Griffe Cinglante": {
  "fr": "Griffe Cinglante",
  "en": "Lashing Claw",
  "es": "Garra Azotadora",
  "pt": "Garra de Chicote",
  "de": "Zupackende Kralle"
 },
 "Corbeau": {
  "fr": "Corbeau",
  "en": "Crow",
  "es": "Cuervo",
  "pt": "Corvo",
  "de": "Rabe"
 },
 "Fouet": {
  "fr": "Fouet",
  "en": "Whip",
  "es": "Látigo",
  "pt": "Chicote",
  "de": "Peitsche"
 },
 "Griffe Spectrale": {
  "fr": "Griffe Spectrale",
  "en": "Ghostly Claw",
  "es": "Garra Espectral",
  "pt": "Garra Espectral",
  "de": "Geisterklaue"
 },
 "Pelle Massacrante": {
  "fr": "Pelle Massacrante",
  "en": "Slaughtering Shovel",
  "es": "Pala Masacrante",
  "pt": "Pá Massacrante",
  "de": "Mörderschaufel"
 },
 "Pelle du Jugement": {
  "fr": "Pelle du Jugement",
  "en": "Shovel of Judgement",
  "es": "Pala del Juicio",
  "pt": "Pá de Julgamento",
  "de": "Schaufel der Verurteilung"
 },
 "Roulage de Pelle": {
  "fr": "Roulage de Pelle",
  "en": "Shovel Kiss",
  "es": "Jarabe de Pala",
  "pt": "Beijo da Pá",
  "de": "Herumwirbelnde Schaufel"
 },
 "Désinvocation": {
  "fr": "Désinvocation",
  "en": "Unsummoning",
  "es": "Desinvocación",
  "pt": "Desinvocação",
  "de": "Rückruf"
 },
 "Force de l'Age": {
  "fr": "Force de l'Age",
  "en": "Prime of Life",
  "es": "Madurez",
  "pt": "Melhor da vida",
  "de": "Kraft des Alters"
 },
 "Remblai": {
  "fr": "Remblai",
  "en": "Mound",
  "es": "Terraplenado",
  "pt": "Aterro",
  "de": "Aufhäufen"
 },
 "Pelle Fantomatique": {
  "fr": "Pelle Fantomatique",
  "en": "Ghostly Shovel",
  "es": "Pala Fantasmal",
  "pt": "Pá Espectral",
  "de": "Phantomschaufel"
 },
 "Lancer de Pièces": {
  "fr": "Lancer de Pièces",
  "en": "Coins Throwing",
  "es": "Lanzamiento de Monedas",
  "pt": "Arremesso de Moedas",
  "de": "Münzenwurf"
 },
 "Lancer de Pelle": {
  "fr": "Lancer de Pelle",
  "en": "Shovel Throwing",
  "es": "Lanzamiento de Pala",
  "pt": "Arremesso de Pá",
  "de": "Schaufel werfen"
 },
 "Frappe de Xélor": {
  "fr": "Frappe de Xélor",
  "en": "Xelor's Punch",
  "es": "Golpe de Xelor",
  "pt": "Soco de Xelor",
  "de": "Faust von Xélor"
 },
 "Horloge": {
  "fr": "Horloge",
  "en": "Clock",
  "es": "Reloj de Pared",
  "pt": "Relógio",
  "de": "Uhrwerk"
 },
 "Poussière Temporelle": {
  "fr": "Poussière Temporelle",
  "en": "Temporal Dust",
  "es": "Polvo Temporal",
  "pt": "Poeira Temporal",
  "de": "Zeitstaub"
 },
 "Flétrissement": {
  "fr": "Flétrissement",
  "en": "Shriveling",
  "es": "Marchitación",
  "pt": "Encolhimento",
  "de": "Verwelken"
 },
 "Rayon Obscur": {
  "fr": "Rayon Obscur",
  "en": "Dark Ray",
  "es": "Rayo Oscuro",
  "pt": "Raio Sombrio",
  "de": "Dunkelstrahl"
 },
 "Sablier de Xélor": {
  "fr": "Sablier de Xélor",
  "en": "Xelor's Sandglass",
  "es": "Reloj de Arena de Xelor",
  "pt": "Ampulheta Xelor",
  "de": "Sanduhr von Xélor"
 },
 "Gelure": {
  "fr": "Gelure",
  "en": "Frostbite",
  "es": "Congelación",
  "pt": "Mordida Gélida",
  "de": "Einfrieren"
 },
 "Aiguille": {
  "fr": "Aiguille",
  "en": "Hand",
  "es": "Aguja",
  "pt": "Ferrão",
  "de": "Zeiger"
 },
 "Destin d'Ecaflip": {
  "fr": "Destin d'Ecaflip",
  "en": "Fate of Ecaflip",
  "es": "Destino de Zurcarák",
  "pt": "Destino de Ecaflip",
  "de": "Ecaflips Schicksal"
 },
 "Rekop": {
  "fr": "Rekop",
  "en": "Rekop",
  "es": "Rekop",
  "pt": "Rekop",
  "de": "Rekop"
 },
 "Griffe de Ceangal": {
  "fr": "Griffe de Ceangal",
  "en": "Claw of Ceangal",
  "es": "Garra de Ceangal",
  "pt": "Garra de Ceangal",
  "de": "Klaue von Ceangal"
 },
 "Griffe Joueuse": {
  "fr": "Griffe Joueuse",
  "en": "Playful Claw",
  "es": "Garra Juguetona",
  "pt": "Garra Divertida",
  "de": "Spielkralle"
 },
 "Esprit Félin": {
  "fr": "Esprit Félin",
  "en": "Feline Spirit",
  "es": "Espíritu Felino",
  "pt": "Espírito Felino",
  "de": "Katzengeist"
 },
 "Langue Râpeuse": {
  "fr": "Langue Râpeuse",
  "en": "Rough Tongue",
  "es": "Lengua Raspadora",
  "pt": "Língua Áspera",
  "de": "Raue Zunge"
 },
 "Topkaj": {
  "fr": "Topkaj",
  "en": "Topkaj",
  "es": "Topkaj",
  "pt": "Topkaj",
  "de": "Topkaj"
 },
 "Tout ou rien": {
  "fr": "Tout ou rien",
  "en": "All or Nothing",
  "es": "Todo o Nada",
  "pt": "Tudo ou Nada",
  "de": "Alles oder nichts"
 },
 "Bluff": {
  "fr": "Bluff",
  "en": "Bluff",
  "es": "Farol",
  "pt": "Blefe",
  "de": "Bluff"
 },
 "Pile ou Face": {
  "fr": "Pile ou Face",
  "en": "Heads or Tails",
  "es": "Cara o Cruz",
  "pt": "Cara ou coroa",
  "de": "Kopf oder Zahl"
 },
 "Mot Blessant": {
  "fr": "Mot Blessant",
  "en": "Wounding Word",
  "es": "Palabra Hiriente",
  "pt": "Palavra do Poder: Dor",
  "de": "Verletzendes Wort"
 },
 "Mot Interdit": {
  "fr": "Mot Interdit",
  "en": "Forbidden Word",
  "es": "Palabra Prohibida",
  "pt": "Palavra do Poder: Explosão",
  "de": "Verbotenes Wort"
 },
 "Colère de Iop": {
  "fr": "Colère de Iop",
  "en": "Iop's Wrath",
  "es": "Ira de Yopuka",
  "pt": "Cólera de Iop",
  "de": "Iops Wut"
 },
 "Epée de Iop": {
  "fr": "Epée de Iop",
  "en": "Sword of Iop",
  "es": "Espada de Yopuka",
  "pt": "Espada de Iop",
  "de": "Iops Schwert"
 },
 "Concentration": {
  "fr": "Concentration",
  "en": "Concentration",
  "es": "Concentración",
  "pt": "Concentração",
  "de": "Konzentration"
 },
 "Epée Céleste": {
  "fr": "Epée Céleste",
  "en": "Celestial Sword",
  "es": "Espada Celeste",
  "pt": "Espada Celestial",
  "de": "Himmlisches Schwert"
 },
 "Tempête de Puissance": {
  "fr": "Tempête de Puissance",
  "en": "Strengthstorm",
  "es": "Tempestad de Potencia",
  "pt": "Tempestade de Poder",
  "de": "Sturm der Macht"
 },
 "Epée du Jugement": {
  "fr": "Epée du Jugement",
  "en": "Sword of Judgement",
  "es": "Espada del Juicio",
  "pt": "Espada de Julgamento",
  "de": "Schwert der Verurteilung"
 },
 "Couper": {
  "fr": "Couper",
  "en": "Cut",
  "es": "Corte",
  "pt": "Corte",
  "de": "Schneiden"
 },
 "Epée Destructrice": {
  "fr": "Epée Destructrice",
  "en": "Destructive Sword",
  "es": "Espada Destructora",
  "pt": "Espada Destrutiva",
  "de": "Zerstörerisches Schwert"
 },
 "Epée du destin": {
  "fr": "Epée du destin",
  "en": "Sword of Fate",
  "es": "Espada del Destino",
  "pt": "Espada de Destino",
  "de": "Schicksalsschwert"
 },
 "Epée Divine": {
  "fr": "Epée Divine",
  "en": "Divine Sword",
  "es": "Espada Divina",
  "pt": "Espada Divina",
  "de": "Göttliches Schwert"
 },
 "Intimidation": {
  "fr": "Intimidation",
  "en": "Intimidation",
  "es": "Intimidación",
  "pt": "Intimidação",
  "de": "Einschüchterung"
 },
 "Pression": {
  "fr": "Pression",
  "en": "Pressure",
  "es": "Presión",
  "pt": "Pressão",
  "de": "Druck"
 },
 "Flèche Explosive": {
  "fr": "Flèche Explosive",
  "en": "Explosive Arrow",
  "es": "Flecha Explosiva",
  "pt": "Flecha Explosiva",
  "de": "Explosionspfeil"
 },
 "Flèche Ralentissante": {
  "fr": "Flèche Ralentissante",
  "en": "Slow Down Arrow",
  "es": "Flecha Ralentizante",
  "pt": "Flecha de Desaceleração",
  "de": "Verlangsamungspfeil"
 },
 "Flèche Destructrice": {
  "fr": "Flèche Destructrice",
  "en": "Destructive Arrow",
  "es": "Flecha Destructora",
  "pt": "Flecha Destrutiva",
  "de": "Zerstörender Pfeil"
 },
 "Flèche Persécutrice": {
  "fr": "Flèche Persécutrice",
  "en": "Tormenting Arrow",
  "es": "Flecha Perseguidora",
  "pt": "Olho de Lince",
  "de": "Heimsuchender Pfeil"
 },
 "Flèche Cinglante": {
  "fr": "Flèche Cinglante",
  "en": "Lashing Arrow",
  "es": "Flecha Azotadora",
  "pt": "Flecha Cegante",
  "de": "Peitschender Pfeil"
 },
 "Flèche Harcelante": {
  "fr": "Flèche Harcelante",
  "en": "Plaguing Arrow",
  "es": "Flecha Acosadora",
  "pt": "Flecha da Moléstia",
  "de": "Plagender Pfeil"
 },
 "Flèche Punitive": {
  "fr": "Flèche Punitive",
  "en": "Punitive Arrow",
  "es": "Flecha Castigadora",
  "pt": "Flecha Punitiva",
  "de": "Strafender Pfeil"
 },
 "Flèche d'Immobilisation": {
  "fr": "Flèche d'Immobilisation",
  "en": "Paralyzing Arrow",
  "es": "Flecha Inmovilizadora",
  "pt": "Flecha de Imobilização",
  "de": "Lähmpfeil"
 },
 "Flèche d'Expiation": {
  "fr": "Flèche d'Expiation",
  "en": "Atonement Arrow",
  "es": "Flecha de Expiación",
  "pt": "Flecha de Expiação",
  "de": "Sühnepfeil"
 },
 "Flèche Enflammée": {
  "fr": "Flèche Enflammée",
  "en": "Burning Arrow",
  "es": "Flecha Flamígera",
  "pt": "Flecha Chama",
  "de": "Flammenpfeil"
 },
 "Flèche Glacée": {
  "fr": "Flèche Glacée",
  "en": "Frozen Arrow",
  "es": "Flecha Helada",
  "pt": "Flecha de Gelo",
  "de": "Eispfeil"
 },
 "Flèche Magique": {
  "fr": "Flèche Magique",
  "en": "Magic Arrow",
  "es": "Flecha Mágica",
  "pt": "Flecha Mágica",
  "de": "Magischer Pfeil"
 },
 "Flèche Empoisonnée": {
  "fr": "Flèche Empoisonnée",
  "en": "Poisoned Arrow",
  "es": "Flecha Envenenada",
  "pt": "Flecha Envenenada",
  "de": "Giftpfeil"
 },
 "Flèche de Recul": {
  "fr": "Flèche de Recul",
  "en": "Retreat Arrow",
  "es": "Flecha de Retroceso",
  "pt": "Flecha de Recuo",
  "de": "Rückstoßpfeil"
 },
 "Feu de Brousse": {
  "fr": "Feu de Brousse",
  "en": "Bush Fire",
  "es": "Fuego Montés",
  "pt": "Incêndio Florestal",
  "de": "Buschfeuer"
 },
 "Herbe Folle": {
  "fr": "Herbe Folle",
  "en": "Wild Grass",
  "es": "Hierba Loca",
  "pt": "Erva Selvagem",
  "de": "Wuchernde Gräser"
 },
 "Ronces Agressives": {
  "fr": "Ronces Agressives",
  "en": "Aggressive Brambles",
  "es": "Zarzas Agresivas",
  "pt": "Sarça Agressiva",
  "de": "Aggressive Ranken"
 },
 "Vent Empoisonné": {
  "fr": "Vent Empoisonné",
  "en": "Poisoned Wind",
  "es": "Viento Envenenado",
  "pt": "Vento Envenenado",
  "de": "Giftiger Windstrom"
 },
 "Ronces Multiples": {
  "fr": "Ronces Multiples",
  "en": "Manifold Bramble",
  "es": "Zarzas Múltiples",
  "pt": "Sarça Múltipla",
  "de": "Rankengewirr"
 },
 "Tremblement": {
  "fr": "Tremblement",
  "en": "Earthquake",
  "es": "Temblor",
  "pt": "Terremoto",
  "de": "Beben"
 },
 "Larme": {
  "fr": "Larme",
  "en": "Tear",
  "es": "Lágrima",
  "pt": "Lágrima",
  "de": "Träne"
 },
 "Ronce": {
  "fr": "Ronce",
  "en": "Bramble",
  "es": "Zarza",
  "pt": "Sarça",
  "de": "Ranken"
 },
 "Furie": {
  "fr": "Furie",
  "en": "Fury",
  "es": "Furia",
  "pt": "Fúria",
  "de": "Raserei"
 },
 "Assaut": {
  "fr": "Assaut",
  "en": "Assault",
  "es": "Asalto",
  "pt": "Assalto",
  "de": "Sturmangriff"
 },
 "Pied du Sacrieur": {
  "fr": "Pied du Sacrieur",
  "en": "Sacrier's Foot",
  "es": "Pie del Sacrógrito",
  "pt": "Bica de Sacrier",
  "de": "Sacrieurs Fuß"
 },
 "Pandatak": {
  "fr": "Pandatak",
  "en": "Pandatak",
  "es": "Pandatak",
  "pt": "Pandatak",
  "de": "Pandattak"
 },
 "Flasque Explosive": {
  "fr": "Flasque Explosive",
  "en": "Explosive Flask",
  "es": "Frasco Explosivo",
  "pt": "Frasco Explosivo",
  "de": "Explosiver Flachmann"
 },
 "Vague à Lame": {
  "fr": "Vague à Lame",
  "en": "Melancholy",
  "es": "Ola Marejadora",
  "pt": "Melancolia",
  "de": "Welle der Traurigkeit"
 },
 "Souffle Alcoolisé": {
  "fr": "Souffle Alcoolisé",
  "en": "Alcoholic Breath",
  "es": "Soplido Alcoholizado",
  "pt": "Golpe Eufórico",
  "de": "Alkoholatem"
 },
 "Gueule de Bois": {
  "fr": "Gueule de Bois",
  "en": "Hangover",
  "es": "Resaca",
  "pt": "Ressaca",
  "de": "Brummschädel"
 },
 "Poing Enflammé": {
  "fr": "Poing Enflammé",
  "en": "Blazing Fist",
  "es": "Puño Flamígero",
  "pt": "Punho Flamejante",
  "de": "Flammende Faust"
 }
}
