# Generated by Django 5.1.14 on 2026-05-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0014_char_game_version'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='char',
            name='chardata_char_shared_deleted_idx',
        ),
        migrations.RemoveIndex(
            model_name='char',
            name='chardata_char_shared_views_idx',
        ),
        migrations.RemoveIndex(
            model_name='char',
            name='chardata_char_shared_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='char',
            name='chardata_char_shared_modified_idx',
        ),
        migrations.AddField(
            model_name='char',
            name='empty_slots',
            field=models.BinaryField(default=b''),
        ),
    ]
