# Generated by Django 5.1.14 on 2026-05-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0015_add_empty_slots_to_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='stat_overrides',
            field=models.BinaryField(default=b''),
        ),
    ]
