# Generated by Django 6.0.5 on 2026-05-27 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0017_buildcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useralias',
            name='notify_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment / insult'), ('off_topic', 'Off-topic'), ('other', 'Other')], default='other', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chardata.buildcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['comment', 'processed'], name='chardata_co_comment_c7ba17_idx'), models.Index(fields=['processed', 'created_time'], name='chardata_co_process_aa26b5_idx')],
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
