# Generated by Django 6.0.5 on 2026-05-27 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0018_useralias_notify_comments_commentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('game_version', models.CharField(default='dofus3', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'game_version', 'added_time'], name='chardata_wo_user_id_0c6316_idx')],
                'unique_together': {('user', 'item_id', 'game_version')},
            },
        ),
    ]
