# Generated by Django 6.0.5 on 2026-05-27 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0020_userfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('display_name', models.CharField(max_length=40)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='chardata.char')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'char'], name='chardata_bu_name_2dd2fb_idx')],
                'unique_together': {('char', 'name')},
            },
        ),
    ]
