# Generated by Django 6.0.5 on 2026-06-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0021_buildtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutioncounter',
            name='game_version',
            field=models.CharField(db_index=True, default='dofus3', max_length=20),
        ),
    ]
