# Generated by Django 6.0.5 on 2026-06-10 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0022_solutioncounter_game_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('game_version', models.CharField(default='dofus3', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('custom_stats', models.TextField(blank=True, default='')),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chardata.inventoryfolder')),
            ],
        ),
        migrations.AddIndex(
            model_name='inventoryfolder',
            index=models.Index(fields=['user', 'game_version', 'name'], name='chardata_in_user_id_58fb32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryfolder',
            unique_together={('user', 'name', 'game_version')},
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['folder', 'added_time'], name='chardata_in_folder__3a063d_idx'),
        ),
    ]
