# Generated by Django 6.0.5 on 2026-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0023_inventoryfolder_inventoryitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralias',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
