# Generated by Django 6.0.5 on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0024_useralias_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_version', models.CharField(db_index=True, default='dofus3', max_length=20)),
                ('minimal_solution', models.BinaryField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_generations', to='chardata.char')),
            ],
            options={
                'ordering': ['-created_time', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='solutiongeneration',
            index=models.Index(fields=['char', 'created_time'], name='chardata_so_char_id_7a7e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='solutiongeneration',
            index=models.Index(fields=['char', 'game_version', 'created_time'], name='chardata_so_char_id_d4f09c_idx'),
        ),
    ]
