# Generated by Django 6.0.7 on 2026-07-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0026_utf8mb4_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
