# Generated by Django 6.0.7 on 2026-08-01 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0032_sitesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='char',
            index=models.Index(fields=['game_version', 'link_shared', 'deleted', '-created_time'], name='char_shared_browse'),
        ),
    ]
