# Generated by Django 6.0.7 on 2026-08-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0033_char_char_shared_browse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='colors',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
    ]
