# Generated by Django 6.0.7 on 2026-08-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0034_alter_char_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=190, unique=True)),
                ('window_start', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
