# Generated by Django 6.0.8 on 2026-08-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0035_ratecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('count', models.BigIntegerField(default=0)),
            ],
            options={
                'unique_together': {('day', 'language')},
            },
        ),
        migrations.CreateModel(
            name='VisitSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('source', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=40)),
                ('campaign', models.CharField(blank=True, max_length=60)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('count', models.BigIntegerField(default=0)),
            ],
            options={
                'unique_together': {('day', 'source', 'medium', 'campaign', 'language', 'country')},
            },
        ),
    ]
