# Generated by Django 6.0.8 on 2026-08-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0036_supportclick_visitsource'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supportclick',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='supportclick',
            name='source',
            field=models.CharField(default='support', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='supportclick',
            unique_together={('day', 'language', 'source')},
        ),
    ]
