# Generated by Django 6.0.8 on 2026-08-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0037_alter_supportclick_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInSharedBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ankama_id', models.IntegerField()),
                ('game_version', models.CharField(default='dofus3', max_length=20)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chardata.char')),
            ],
            options={
                'unique_together': {('ankama_id', 'game_version', 'char')},
            },
        ),
    ]
