# Generated by Django 6.0.8 on 2026-08-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0038_iteminsharedbuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ankama_id', models.IntegerField()),
                ('game_version', models.CharField(default='dofus3', max_length=20)),
                ('builds', models.IntegerField(default=0)),
                ('eligible', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('ankama_id', 'game_version')},
            },
        ),
    ]
