# Generated by Django 6.0.8 on 2026-09-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0039_itempopularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='auto_publish',
            field=models.BooleanField(default=False),
        ),
    ]
