# Generated by Django 6.0.8 on 2026-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0040_char_auto_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='created_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='char',
            name='solved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='char',
            name='solved_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='solutiongeneration',
            name='data_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
