# Generated by Django 6.0.8 on 2026-09-24 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0044_refill_stuff_time_of_visited_builds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_version', models.CharField(default='dofus3', max_length=20)),
                ('ingredient_ankama_id', models.IntegerField()),
                ('ingredient_subtype', models.CharField(max_length=32)),
                ('owned', models.IntegerField(default=0)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'game_version'], name='chardata_wo_user_id_2a85fb_idx')],
                'unique_together': {('user', 'game_version', 'ingredient_ankama_id', 'ingredient_subtype')},
            },
        ),
    ]
