# Generated by Django 6.0.8 on 2026-09-25 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0045_workshopstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopUndo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_version', models.CharField(default='dofus3', max_length=20)),
                ('workshop_item_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('stock_deltas', models.JSONField(default=list)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_time'], name='chardata_wo_user_id_bfaefb_idx')],
                'unique_together': {('user', 'workshop_item_id')},
            },
        ),
    ]
