# Generated by Django 6.0.8 on 2026-09-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chardata', '0046_workshopundo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSourceHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('source', models.CharField(max_length=20)),
                ('host', models.CharField(blank=True, max_length=190)),
                ('game_version', models.CharField(default='dofus3', max_length=20)),
                ('attempts', models.BigIntegerField(default=0)),
                ('imported', models.BigIntegerField(default=0)),
            ],
            options={
                'unique_together': {('day', 'source', 'host', 'game_version')},
            },
        ),
    ]
